
// <auto-generated />
// This file was generated by a R4Mvc.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the r4mvc.json file (i.e. the settings file), save it and rebuild.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo.Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 108
using System.CodeDom.Compiler;
using Microsoft.AspNet.Mvc;
using System.Threading.Tasks;

namespace R4MvcHostApp.Controllers
{
    public partial class AccountController
    {
        public AccountController()
        {
        }
    }

    public partial class HomeController
    {
        public HomeController()
        {
        }
    }
}

namespace R4MVC
{
    public class Dummy
    {
        private Dummy()
        {
        }

        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 1591, 3008, 3009, 108

