// <auto-generated />
// This file was generated by R4Mvc.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the r4mvc.json file (i.e. the settings file), save it and run the generator tool again.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo.Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using R4Mvc;
using AspNetSimple;

namespace R4Mvc
{
    public partial class NoModelModel : IR4ActionResult
    {
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        string IR4ActionResult.Protocol => null;
        [GeneratedCode("R4Mvc", "1.0")]
        RouteValueDictionary m_RouteValueDictionary = new RouteValueDictionary{{"Page", "/NoModel"}};
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        RouteValueDictionary IR4ActionResult.RouteValueDictionary => m_RouteValueDictionary;
    }
}
#pragma warning restore 1591, 3008, 3009, 0108
